title: hy's blog
sub_title: kimhyhy.github.io
github_username: hy
highlighter: rouge
svg:
  optimize: true
# theme: minima
highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/

